### ISSUE TITLE
MEMORY_LIMIT_EXCEEDED error while uploading huge file on click house.

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/clickhouse-java#1412] opened 2023-08-03 05:23 UTC
### MEMORY_LIMIT_EXCEEDED error while uploading huge file on click house.

 I am using the below method to upload the local file on click house.

```
static long insert(String tableName, String csvFilePath) throws Exception {
        ClickHouseNode server = getServer();
        try (BufferedInputStream bufferedInputStream = new BufferedInputStream(new FileInputStream(csvFilePath))) {
            ClickHousePassThruStream stream = ClickHousePassThruStream.of(
                    bufferedInputStream,
                    ClickHouseCompression.NONE,
                    0,
                    ClickHouseFormat.CSVWithNames
            );
            CompletableFuture<ClickHouseResponseSummary> load = ClickHouseClient.load(server, tableName, stream);
            ClickHouseResponseSummary clickHouseResponse = load.get();
            return clickHouseResponse.getWrittenRows();
        } catch (Exception e) {
            System.out.println("Failed to  load");
            e.printStackTrace();
            throw new Exception();
        }
    }
```
But on huge files, it failed with memory issues, Most failures occurred on the file that contained more than 300 columns.

```
ERROR [2023-07-27 06:20:36,451] com.datoin.library.dataset.sql.utility.commons.abstracts.sql.AbstractDBEngine: Failed to load dataset
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 241. DB::Exception: Memory limit (total) exceeded:
would use 3.36 GiB (attempt to allocate chunk of 4360384 bytes), maximum: 3.24 GiB. OvercommitTracker decision: Query was selected to stop by
 OvercommitTracker. (MEMORY_LIMIT_EXCEEDED) (version 23.6.2.18 (official build))
, server ClickHouseNode [uri=http://localhost:8123/cayleytest95814, options={connect_timeout=5000000,socket_timeout=5000000}]@75218225
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
```

Is there any way to upload huge files 30-40GB files on Clickhouse without any memory issues? which directly reads from the disk and uploads on click house. Optimal way in terms of

**Comment by mshustov** [comment] 2023-08-15 11:09
duplicate of https://github.com/ClickHouse/clickhouse-java/issues/1401

**Closed by mshustov** 2023-08-15 11:09 UTC
Labels: bug
