### ISSUE TITLE
It spent about 40 seconds loading jdbc-driver after 1.6.0-patch3

### ISSUE THREAD

**Issue by AlexYangYu** [ClickHouse/clickhouse-java#1731] opened 2024-07-10 15:27 UTC
### Describe the bug
I found the clickhouse jdbc driver spentd a lot of time(about 40 seconds) for loading after the version 1.6.0-patch3.

### Steps to reproduce
1. enable DEBUG level of log
2. run springboot app using 1.6.0-patch3
```Plain
2024-07-10 23:18:23.263 CST+08:00 DEBUG [main] [] c.clickhouse.jdbc.ClickHouseDriver - ClickHouse Driver 0.6.0.0(JDBC: 4.2.0.0) registered
2024-07-10 23:18:23.269 CST+08:00 DEBUG [main] [] o.s.b.f.s.DefaultListableBeanFactory - Autowiring by type from bean name 'sqlSessionFactory' via factory method to bean named 'dataSource'
```
load quickly

3. run springboot app using 1.6.0-patch4  or above
```Plain
2024-07-10 23:24:51.714 CST+08:00 DEBUG [main] [] c.clickhouse.jdbc.ClickHouseDriver - ClickHouse Driver 0.6.0.0(JDBC: 4.2.0.0) registered
2024-07-10 23:25:33.799 CST+08:00 DEBUG [main] [] o.s.b.f.s.DefaultListableBeanFactory - Autowiring by type from bean name 'sqlSessionFactory' via factory method to bean named 'dataSource'
```
spent about 40 seconds

**Comment by mshustov** [comment] 2024-07-11 08:29
Duplicate of https://github.com/ClickHouse/clickhouse-java/issues/1729?

**Comment by mshustov** [comment] 2024-07-20 07:13
Could you retest the last release with a fix for https://github.com/ClickHouse/clickhouse-java/issues/1729? Please reopen if you spot any problems.

**Closed by mshustov** 2024-07-20 07:13 UTC
Labels: bug
