### ISSUE TITLE
Unsupported data type: JSON

### ISSUE THREAD

**Issue by aarcha123** [ClickHouse/clickhouse-java#1023] opened 2022-07-29 05:43 UTC
Using the below snippet results in "Unsupported data type: JSON:"  using 0.3.2.patch11

```java 
PreparedStatement pstmt = connection.prepareStatement("INSERT INTO json_demo SELECT id,details from INPUT('id UInt8, details JSON')"); `
    pstmt.setInt(1, 20);
pstmt.setObject(2, "{\"type\": \"Region\"}");
pstmt.addBatch();
pstmt.executeBatch();
```

Table definition 
```sql
CREATE TABLE json_demo
( id UInt8,
details JSON)
ENGINE = MergeTree()
PRIMARY KEY (id)
```

Stack trace:

```java 
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported data type: JSON
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.serialize(ClickHouseRowBinaryProcessor.java:484)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:333)
```

**Comment by zhicwu** [comment] 2022-07-29 06:41
Hi @aarcha123, thanks for the report. It looks like now ClickHouse supports string format JSON object, which is way better than constructing a complex object in client. I'll update data type mapping accordingly in next release. Meanwhile, the workaround is simply change `JSON` to `String` in your **insert** query.

**Comment by aarcha123** [comment] 2022-07-29 14:35
Thank you @zhicwu

**Comment by emelyanovkr** [comment] 2024-04-06 10:41
@zhicwu, is there any way to insert a JSON'ed string like this:
`{"timestamp":"2024-04-06 10:26:20","severity":"INFO","thread":"pool-2-thread-11","message":"Compression of 29.29 MB of data with rate 28.94 MB/sec finished in 1.01 sec.","mdc_fields":{"compression_rate":"28.942567086502496","data_size":"29.289877891540527"},"exception":{"stackTrace":""}}
`

by using JavaClient?
```java
 public void insertString(String data) {
    try (ClickHouseResponse response =
        client
            .write(server)
            .query("INSERT INTO tickets_data_db.tickets_logs SELECT c1 FROM input('c1 String') FORMAT JSONAsString")
            .params(data)
            .executeAndWait()) {
      ClickHouseResponseSummary summary = response.getSummary();
      System.out.println("WRITTEN BYTES - " + summary.getWrittenBytes());
    } catch (ClickHouseException e) {
      System.out.println("FAILED TO INSERT STRING - " + e.getMessage());
      throw new RuntimeException(e);
    }
  }
```
data - log message
This results in  written bytes = 0 and nothing more.

By using .data and ClickHousePassThruStream like this:
```java
  public void insertString(String data) {
    try (ClickHouseResponse response =
        client
            .write(server)
            .query("INSERT INTO tickets_data_db.tickets_logs")
            .data(
                ClickHousePassThruStream.of(
                    new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8)),
                    ClickHouseCompression.NONE,
                    ClickHouseFormat.JSONAsString))
            .executeAndWait()) {
      ClickHouseResponseSummary summary = response.getSummary();
      System.out.println("WRITTEN BYTES - " + summary.getWrittenBytes());
    } catch (ClickHouseException e) {
      System.out.println("FAILED TO INSERT STRING - " + e.getMessage());
      throw new RuntimeException(e);
    }
  }
```
Results in an Exception - `Caused by: com.clickhouse.client.ClickHouseException: Code: 399. DB::Exception: Format JSONAsString is not suitable for output. (FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT) (version 24.1.2.10900 (official build))`

_ClickHouseFormat.JSONStrings or .JSON_ results in `Only Input Format allowed for mutations`. So what format exaclty should I specify?

**Comment by mzitnik** [comment] 2024-10-28 13:46
Duplicate of #1833

**Closed by mzitnik** 2024-10-28 13:46 UTC
Labels: enhancement

**Comment by unoexperto** [comment] 2025-01-22 14:14
@chernser @mzitnik @zhicwu 

Folks, I apologize for asking here but I thought it doesn't warrant opening separate issue. How do I pass "allow_experimental_json_type" when I use client V1 ? Here is how I create the client

```
ClickHouseClient
                .builder()
                .config(
                    ClickHouseConfig(
                        mapOf(
                            ClickHouseClientOption.USE_BINARY_STRING to true,
                            ClickHouseClientOption.USE_COMPILATION to true,
                            ClickHouseClientOption.fromKey(ServerSettings.INPUT_FORMAT_BINARY_READ_JSON_AS_STRING) to true,
                            ClickHouseClientOption.fromKey(ServerSettings.OUTPUT_FORMAT_BINARY_WRITE_JSON_AS_STRING) to true,
                            ClickHouseClientOption.fromKey("allow_experimental_json_type") to "1",
                            ClickHouseClientOption.fromKey("allow_experimental_json_type") to 1,
                            ClickHouseClientOption.fromKey("allow_experimental_json_type") to true,
                        )
                    )
                )
                .build()
```

I'm still getting `Cannot create column with type 'JSON' because experimental JSON type is not allowed. Set setting allow_experimental_json_type = 1 in order to allow it.` exception on attempt to create table :(
