### ISSUE TITLE
I guess java does not pass input_format_csv_allow_variable_number_of_columns

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/clickhouse-java#1467] opened 2023-10-10 04:32 UTC
### Example File 1
```
col1,col2,col3
1,2,3
3,4,5
6,7,8,9
1,2,3
1,2,3
3,4,5
1,2,3
3,4,5
```

### Example File 1
```
col1,col2,col3
1,2,3
3,4,5
6,7
1,2,3
1,2,3
3,4,5
1,2,3
3,4,5
```

### Code example
```
insert code

static long insert(String tableName, String csvFilePath) throws Exception {
        ClickHouseNode server = ClickHouseNode.builder()
                .host(System.getProperty("chHost", "localhost"))
                .port(ClickHouseProtocol.HTTP, Integer.getInteger("chPort", 8123))
                .database("ShabirBhat_project")
                .addOption("connect_timeout", String.valueOf(2000 * 1000))
                .addOption("socket_timeout", String.valueOf(2000 * 1000))
                .addOption("input_format_csv_allow_variable_number_of_columns", String.valueOf("1"))
.credentials(ClickHouseCredentials.fromUserAndPassword(
                        System.getProperty("chUser", "default"), System.getProperty("chPassword", "")))
                .build();
        System.out.println(server);
        try (BufferedInputStream bufferedInputStream = new BufferedInputStream(new FileInputStream(csvFilePath))) {
            ClickHousePassThruStream stream = ClickHousePassThruStream.of(
                    bufferedInputStream,
                    ClickHouseCompression.NONE,
                    0,
                    ClickHouseFormat.CSVWithNames
            );
            System.out.println(server.getConfig().toString());
            CompletableFuture<ClickHouseResponseSummary> load = ClickHouseClient.load(server, tableName, stream);
            ClickHouseResponseSummary clickHouseResponse = load.get();
            System.out.println(clickHouseResponse.toString());
            return clickHouseResponse.getWrittenRows();
        } catch (Exception e) {
            System.out.println("Failed to  load");
            e.printStackTrace();
            throw new Exception();
        }

```
### Error log
```
Failed to  load
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 117. DB::Exception: Expected end of line: (at row 3)
: 
Row 2:
Column 0,   name: col1,                               type: Nullable(Int64),   parsed text: <EMPTY>

.
.
.
ERROR: There is no line feed. "s" found instead.
 It's like your file has more columns than expected.
And if your file has the right number of columns, maybe it has an unquoted string value with a comma.
```

With `input_format_csv_allow_variable_number_of_columns=1` setting it should be able to insert the data into table. Or there may be another way to set input_format_csv_allow_variable_number_of_columns setting in the above code.

**Comment by den-crane** [comment] 2023-10-10 12:20
@shabir1 it's not a bug. See example https://github.com/ClickHouse/clickhouse-java/issues/1046#issuecomment-1220066509

**Comment by mshustov** [comment] 2023-10-13 15:44
closed in favour of https://github.com/ClickHouse/clickhouse-java/issues/1466

**Closed by mshustov** 2023-10-13 15:44 UTC
Labels: question
