### ISSUE TITLE
Selecting huge numbers gives incorrect results

### ISSUE THREAD

**Issue by ne1r0n** [ClickHouse/clickhouse-java#1083] opened 2022-09-13 09:29 UTC
Driver version v0.3.2-patch11

Selecting some huge numbers gives incorrect results.
For example:
`SELECT toUInt64(15369343623947579499) a, toNullable(15369343623947579499) b;`

in dBeaver:
![image](https://user-images.githubusercontent.com/6350825/189865382-7dab3289-3dd0-45b7-a1b5-08ea8a6482fd.png)

in DataGrip:
![image](https://user-images.githubusercontent.com/6350825/189865546-d97fab26-5c5e-41fa-9d92-cdb45082b7a0.png)

**Comment by zhicwu** [comment] 2022-09-13 09:37
Thanks @ne1r0n for reporting the issue. I can reproduce the same issue on latest DBeaver but it works in other DB client like SQuirreL SQL.

Behind the scene, by default JDBC driver maps UInt64 to Java `long` so you may see negative value when calling `ResultSet.getLong()` but you should really call `ResultSet.getObject()` or `ResultSet.getBigDecimal()` instead.

**Comment by zhicwu** [comment] 2022-11-10 00:28
In refactored version, I added Unsigned* classes for unsigned data types(e.g. `com.clickhouse.client.data.UnsignedLong` for UInt64). This was mainly to fix type conversion issues but it may resolve the display issue in most database clients using the driver as well(DataGrip now shows correct result and same for DBeaver).

**Comment by zhicwu** [comment] 2023-05-19 02:17
The issue has been fixed in JDBC driver, but it looks like DBeaver has display issue - dbeaver/dbeaver#20014

**Closed by zhicwu** 2023-05-19 02:17 UTC
Labels: enhancement
