### ISSUE TITLE
`record.getBoolean(columnName)` fails while `record.hasValue(columnName)` succeeds in GenericRecord (version 0.7.0)

### ISSUE THREAD

**Issue by dikshajoshi44** [ClickHouse/clickhouse-java#1971] opened 2024-11-25 09:25 UTC
## Description
I am encountering an issue with the `GenericRecord` interface from the `com.clickhouse.client.api.query` package in version 0.7.0. The method `record.hasValue(columnName)` returns `true`, indicating that the column has a value, but when I call `record.getBoolean(columnName)`, it does not return the expected boolean value.

## Steps to Reproduce
1. Execute the following generic query to retrieve a record from ClickHouse:
   ```sql
   SELECT EXISTS (
       SELECT *
       FROM {table_name}
       WHERE column_name = '{value_placeholder}'
   );
2. if (record.hasValue(columnName)) {
    boolean value = record.getBoolean(columnName); // This is where the issue occurs
}

## Expected Behavior
`record.getBoolean(columnName)` should return the correct boolean value when `record.hasValue(columnName)` returns `true`.


## Environment
- ClickHouse Client version: 0.7.0
- Java version: 17

**Comment by chernser** [comment] 2024-12-04 19:27
Thank you for reporting, @dikshajoshi44 ! 
Will look into it.

**Comment by chernser** [comment] 2024-12-10 06:31
Good day, @dikshajoshi44! 
Is record.getBoolean() returns null or throws an exception? If exception - do you have a stack trace for that? 
Thanks!

**Comment by chernser** [comment] 2024-12-12 23:45
Good day, @dikshajoshi44 ! 
I have not reproduced the issue on latest version `0.7.1-patch1` 
I think, this is duplicate of https://github.com/ClickHouse/clickhouse-java/issues/1908

I'm closing the issue.

**Closed by chernser** 2024-12-12 23:45 UTC
Labels: bug, duplicate, client-api-v2
